CREATE TABLE PARENTS(ID BIGINT PRIMARY KEY, MOTHER_ID BIGINT, NAME VARCHAR(255));
CREATE TABLE ITEM(ID BIGINT PRIMARY KEY,MOTHER_ID BIGINT,FOREIGN KEY (MOTHER_ID) REFERENCES PARENTS, NAME VARCHAR(255), AGE INT);
