INSERT INTO PARENT (ID, MOTHER_ID, NAME) VALUES (1, 1, 'Zamowienie 1');
INSERT INTO PARENT (ID, MOTHER_ID, NAME) VALUES (2, 1, 'Zamowienie 2');
INSERT INTO PARENT (ID, MOTHER_ID, NAME) VALUES (3, 1, 'Zamowienie 3');
INSERT INTO PARENT (ID, MOTHER_ID, NAME) VALUES (4, 1, 'Zamowienie 4');
INSERT INTO PARENT (ID, MOTHER_ID, NAME) VALUES (5, 1, 'Zamowienie 5');

INSERT INTO CHILD (ID, MOTHER_ID, NAME, PRICE) VALUES (1, 1, 'Zel do wlosow', 11.99);
INSERT INTO CHILD (ID, MOTHER_ID, NAME, PRICE) VALUES (2, 2, 'Gumowa kaczuszka', 2.49);
INSERT INTO CHILD (ID, MOTHER_ID, NAME, PRICE) VALUES (3, 2, 'Mapa Imperium Lechitow', 119.00);
INSERT INTO CHILD (ID, MOTHER_ID, NAME, PRICE) VALUES (4, 2, 'Maska antysmogowa', 89.90);
INSERT INTO CHILD (ID, MOTHER_ID, NAME, PRICE) VALUES (5, 3, 'Zlota szczeka dziadka', 999.00);
INSERT INTO CHILD (ID, MOTHER_ID, NAME, PRICE) VALUES (6, 3, 'Tajemniczy przedmiot 1', 324.00);
INSERT INTO CHILD (ID, MOTHER_ID, NAME, PRICE) VALUES (7, 4, 'Tajemniczy przedmiot 2', 654.00);
INSERT INTO CHILD (ID, MOTHER_ID, NAME, PRICE) VALUES (8, 5, 'Tajemniczy przedmiot 3', 12.00);